import sys

fav_things = {"book":"Jitterbug Perfume","song":"Tom Petty - I wont Back Down","tree":"Cedar","organism":"dog"}


print(fav_things["book"])

fav_thing = "book"

print(fav_things[fav_thing])
print(fav_things["tree"])
print(fav_things["organism"])

for x,key in enumerate(fav_things):
    print(x,key,sep="\t")

selecao = input("Digite a chave que voce deseja consultar no dicionario: ")

print(f"A sua chave é {selecao} e o valor dela é {fav_things[selecao]}")

arg1 = input("Digite o nome da sua chave: ")
arg2 = input("Digite o valor da sua chave")

fav_things[arg1] = arg2

for i, chave in enumerate(fav_things):
    print(i, chave, fav_things[chave],sep="\t")

#set pode ser criado com set() ou {}

mySet = {'ATGCCT'}
mySet2 = set('ATGTGGG')

print(mySet)
print(mySet2)

setA = [3,14,15,9,26,5,35,9]
setA = set(setA)
setB = [60, 22, 14, 0, 9]
setB = set(setB)

#diferenca 
print(setA - setB)

#uniao
print(setA | setB)

#intersecao
print(setA & setB)

#diferenca simetrica
print(setA ^ setB)

seq = "GAACTCCAAAAATGAAAACATAGTAGCAATCAAAGCATCCCACTATTTTTTGTCTCTCGTTTCATTAGCGTTGTAAATTACTGATACCCTACTATACCTCTACAAGGCCTTTGTCATCTTTTTACTCAAGTGTGAAATCATCACTTATTGTATGAAGGATGAGCTTTCCGTTCGCTAGTTTGCTGAAAAGGCCTTCTGCAATAAGCTCTCTATTATCTTTAAAAAAACCTGGTTCCTGGTCTTCCATTCTGCTAAAAGCTGTAGGGGTTTTATCACGAGATTCCCGTTGGCATTCTGACTTATTAAAAATGCTTACAGAAGAAATGGATTCTTTAAATGGTCAAATTAATACGTGGACAGATAATAATCCTTTATTAGATGAAATTACGAAGCCATACAGAAAATCTTCAACTCGTTTTTTTCATCCGCTTCTTGTACTTCTAATGTCTAGAGCATCAGTAAATGGGGATCCACCGAGTCAGCAACTATTTCAAAGGTACAAACAACTTGCCCGTGTAACAGAATTGATTCATGCTGCCAATATAATTCATATTAATATTGGAGAAGAACAAAGCAACGAACAGATTAAACTTGCAACGTTGGTTGGAGATTATTTACTCGGAAAGGCGTCTGTTGATTTAGCACATTTAGAAAACAACGCTATTACAGAAATTATGGCTTCTGTTATTGCAAACTTAGTTGAAGGGCACTTCGGAAGCCGACAAAATGGCTCTGTTGGTTTGTCAAACGAACGAACCATCCTTCTGCAATCAGCCTTTATGCCAGCAAAGGCATGTTTATGCGCAAGCATATTGAATAACTCATCACAATACATTAATGATGCGTGTTTCAATTATGGAAAATTTCTAGGCTTATCGCTGCAACTGGCCCATAAGCCTGTATCTCCTGACGCCCAAGTTTTGCAAAAGAATAATGACATTTTGAAAACATATGTTGAGAATGCCAAGAGCTCATTGTCTGTTTTCCCCGATATAGAGGCTAAGCAAGCTCTCATGGAAATCGCTAATAGTGTTTCGAAGTAATCGACAGGTATTGTATCCTGGATTAATATTAGGGTGGCTCATGCATGCTCGTGCAATCGTAACAAATATGTCTTTCTTTTACGAATTTTAACGCTTCAATATAAATCATATTTTTCCTCA"
dictFinal = {}
setSeq = set(seq)

for i in setSeq:
    dictFinal[str(i)] = seq.count(i)

print(dictFinal)